spring.application.name=Nucleus

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/Nucleus}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:password}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

jwt.accessTokenKey=${JWT_ACCESS_TOKEN_KEY:local_access_key}
jwt.refreshTokenKey=${JWT_REFRESH_TOKEN_KEY:local_refresh_key}

aws.s3.accessKey=${AWS_ACCESS_KEY_ID:dummy_key}
aws.s3.secretKey=${AWS_SECRET_ACCESS_KEY:dummy_secret}
aws.s3.region=${AWS_REGION:ap-south-1}
aws.s3.bucketName=${AWS_BUCKET_NAME:nucleus-img-bucket}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER:test@gmail.com}
spring.mail.password=${MAIL_PASS:test_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true