spring.application.name=Nucleus


spring.datasource.url = jdbc:postgresql://localhost:5433/Nucleus
spring.datasource.username = postgres
spring.datasource.password = YMulik@2005

#spring.datasource.url=jdbc:postgresql://pg-67a7ef-yashmulik95-dab6.e.aivencloud.com:21097/defaultdb?sslmode=require
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_KsArIT5CQfONbjV3Mli

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.accessTokenKey = "ndkjbvdhvdgducvydvcuydcvwueyvweudyvweycwdc"
jwt.refreshTokenKey = "jdihdewydfqokwqonnjabxywtdqwrchxjdbudvdtycdytqcxtqwd"

aws.s3.accessKey=AKIA4UVXYXWAPN6TLOCR
aws.s3.secretKey=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
aws.s3.region=ap-south-1
aws.s3.bucketName=nucleus-img-bucket

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yashmulik95@gmail.com
spring.mail.password=aqkx vpne itbu bxog

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

