spring.application.name=Nucleus

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

jwt.accessTokenKey=${JWT_ACCESS_TOKEN_KEY}
jwt.refreshTokenKey=${JWT_REFRESH_TOKEN_KEY}

aws.s3.accessKey=${AWS_ACCESS_KEY_ID}
aws.s3.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.s3.region=${AWS_REGION}
aws.s3.bucketName=${AWS_BUCKET_NAME}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true